services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
      - ./pytest.ini:/code/pytest.ini
      - ./scripts:/code/scripts
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload